version: '3.9'
services:
  web:
    build: .
    container_name: django_app
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app

    ports:
      - "8000:8000"
    env_file:
      - .env
  
    depends_on:
      - db  

  
  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5436:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: test@gmail.com
      PGADMIN_DEFAULT_PASSWORD: test
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
    depends_on:
      - db

volumes:
  postgres-data: